import { Link } from 'react-router-dom'
import LegalPage, { H2 } from '../components/LegalPage'

export default function Terms() {
  return (
    <LegalPage title="Terms of Service" updated="June 2026">
      <p>
        Welcome to LunaCat. These terms govern your use of the LunaCat application
        and service ("LunaCat", "we", "us"). By creating an account or using the
        app, you agree to them. Please read the section on veterinary care
        carefully — it is the most important part.
      </p>

      <H2>LunaCat is not a veterinary service</H2>
      <p>
        <strong>LunaCat is not a veterinarian and does not provide veterinary
        advice, diagnosis, or treatment.</strong> It is a record-keeping and
        observation tool that helps you notice changes in your cat over time. Any
        patterns, trends, or notes the app surfaces are <strong>observational and
        preliminary</strong> — they describe what your logs show, not what is
        medically wrong with your cat.
      </p>
      <p>
        Nothing in LunaCat is a substitute for professional veterinary care. Always
        consult a licensed veterinarian for any concern about your cat's health,
        and seek emergency care immediately if your cat shows signs of distress
        (for example straining to urinate, blood in urine, difficulty breathing,
        collapse, or repeated vomiting). Never delay or disregard veterinary advice
        because of something you read in LunaCat.
      </p>

      <H2>About the "patterns" LunaCat shows</H2>
      <p>
        LunaCat may highlight clusters of changes (for example in weight, appetite,
        or litter-box use) and suggest body areas a vet might look at. These signals
        are generated by rules whose thresholds are <strong>preliminary and have not
        yet been clinically validated or signed off by a veterinarian.</strong> They
        are intended to help you have a better-informed conversation with your vet —
        not to tell you what your cat has. They may be wrong, may miss things, and
        should always be confirmed by a professional.
      </p>

      <H2>Your account and your data</H2>
      <p>
        You are responsible for the accuracy of what you log and for keeping your
        sign-in credentials secure. The data you enter — weights, meals, litter and
        symptom observations, vaccinations, vet visits, uploaded documents — is
        yours. You may request a copy of your data, or its deletion, at any time
        (see the Privacy Policy). Today that request is handled by contacting us;
        an in-app export/delete control is planned.
      </p>

      <H2>Acceptable use</H2>
      <p>
        Use LunaCat only for your own cats and your own records. Do not attempt to
        access another owner's data, disrupt the service, or rely on the app for
        decisions that require a veterinarian.
      </p>

      <H2>No warranty; limitation of liability</H2>
      <p>
        LunaCat is provided "as is", without warranties of any kind. To the maximum
        extent permitted by law, we are not liable for any harm arising from
        reliance on the app's output, including any decision to seek, delay, or
        forgo veterinary care. The responsibility for your cat's health remains with
        you and your veterinarian.
      </p>

      <H2>Changes</H2>
      <p>
        We may update these terms as the product evolves. If the changes are
        material, we will ask you to review and accept them again before continuing
        to use health features.
      </p>

      <H2>Contact</H2>
      <p>
        Questions, data requests, or concerns: reach us through the contact option
        in your profile, or by email at the address listed there.
      </p>

      <p style={{ marginTop: 24, fontSize: 13, color: '#757896' }}>
        See also our <Link to="/privacy" style={{ color: '#6B6BD6' }}>Privacy Policy</Link>.
      </p>
    </LegalPage>
  )
}
